# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-13 13:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True, verbose_name='start_time')),
                ('stop_time', models.DateTimeField(null=True, verbose_name='stop_time')),
                ('comeback_time', models.DateTimeField(null=True, verbose_name='comeback_time')),
                ('finish_time', models.DateTimeField(null=True, verbose_name='finish_time')),
                ('duration', models.DurationField(default=0, verbose_name='duration')),
                ('state', models.CharField(choices=[('IDLE', 'IDLE'), ('RUNNING', 'RUNNING'), ('STOPPED', 'STOPPED'), ('FINISHED', 'FINISHED')], default='IDLE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='TASK-01', max_length=200)),
                ('title', models.CharField(default='This is default task title', max_length=200)),
                ('description', models.TextField(default='This is default task description', max_length=2000)),
                ('task_theme', models.CharField(choices=[('API', 'API'), ('ET', 'ET'), ('IOT', 'IOT'), ('games', 'games')], default='API', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TaskRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependant_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependant_task', to='tasks.Task')),
                ('linked_tasks', models.ManyToManyField(related_name='linked_tasks', to='tasks.Task')),
            ],
        ),
        migrations.AddField(
            model_name='status',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='tasks.Task'),
        ),
        migrations.AddField(
            model_name='status',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
