# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='TASK-01', max_length=200)),
                ('title', models.CharField(default='This is default task title', max_length=200)),
                ('description', models.TextField(default='This is default task description', max_length=2000)),
            ],
        ),
    ]
